name: Run Unit Tests in Databricks Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - "release/*"
    paths-ignore:
      - "terraform/**"
      - ".github/**"
      - "README.md"

jobs:
  development_branch_info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: install-databricks-cli
        uses: databricks/setup-cli@main

      - name: update Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
        run: |
          branch_name=${{ github.ref_name }}
          repo_url=${{ secrets.REPO_URL }}
          git_provider="github"

          function update_and_run_job() {
            job_id=${1}
            job_update_json="{\"job_id\": \"$job_id\", \"new_settings\": {\"git_source\": {\"git_provider\" : \"$git_provider\", \"git_url\": \"$repo_url\", \"git_branch\": \"$branch_name\"}}}"
            databricks jobs update --json "$job_update_json"
            databricks jobs run-now $job_id
          }

          update_and_run_job ${{ secrets.UNIT_TEST_JOB_ID }}
          update_and_run_job ${{ secrets.INTEGRATION_TEST_JOB_ID }}