name: Manual Databricks Deploy
on:
  workflow_dispatch:

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
        DATABRICKS_PROD_REPO_NAME: ${{ vars.DATABRICKS_PROD_REPO_NAME }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: install-databricks-cli
        uses: databricks/setup-cli@main

      - name: Deploy to Prod
        run: |
          databricks repos update "$DATABRICKS_REPO_NAME" --branch "main"