name: Terraform Workflow

on:
  workflow_dispatch:
    

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform chdir
        run: terraform -chdir=terraform/github

      - name: Terraform init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Extract Databricks Job ID
        id: extract_job_id
        run: |
          job_id=$(terraform output -raw databricks_job_id)
          echo "DATABRICKS_JOB_ID=$job_id" >> $GITHUB_ENV

      - name: Save Databricks Job ID to GitHub Secrets
        uses: actions/github-script@v5
        with:
          script: |
            const jobId = process.env.DATABRICKS_JOB_ID;
            const secretName = 'DATABRICKS_JOB_ID';
            const repository = context.repo.owner + '/' + context.repo.repo;
            const token = process.env.GITHUB_TOKEN;
            
            const octokit = github.getOctokit(token);
            await octokit.rest.actions.createOrUpdateRepoSecret({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: secretName,
              encrypted_value: jobId
            });

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
