name: Terraform Workflow

on:
  workflow_dispatch:
   inputs:
      action:
        type: choice
        description: 'Terraform action to perform: apply or destroy'
        required: true
        options:
          - apply
          - destroy
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform chdir
        run: terraform -chdir=terraform/github

      - name: Terraform init
        run: terraform init

      - name: Terraform Apply
        env:
            DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
            DATABRICKS_PAT: ${{ secrets.DATABRICKS_PAT }}
            GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            terraform apply -auto-approve
          elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified"
            exit 1
          fi


