name: Branch Information

on:
  workflow_dispatch:
  push:
    branches:
      - 'development'
      - 'release/*'

jobs:
  development_branch_info:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo Development Branch Name
        run: |
          echo "Development Branch Pushed: ${{ github.ref_name }}"

  release_branch_info:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo Release Branch Name and Current Time
        run: |
          echo "Release Branch Pushed: ${{ github.ref_name }}"
          echo "Current Time: $(date -u)"
