name: Branch Information

on:
  workflow_dispatch:
  push:
    branches:
      - 'development'
      - 'release/*'
    paths-ignore:
      - 'terraform/**'
      - '.github/**'
      - 'README.md'

jobs:
  development_branch_info:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
        run: |
          pip install --upgrade databricks-cli

      - name: Patch Databricks Job
        run: |
          echo "Patching Databricks Job..."
          # Replace 'JOB_ID' with actual Job ID and 'PATCH_CONTENT' with the actual patch content
          databricks jobs patch --job-id JOB_ID --json-file PATCH_CONTENT

      - name: Echo Development Branch Name
        run: |
          echo "Development Branch Pushed: ${{ github.ref_name }}"

  release_branch_info:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo Release Branch Name and Current Time
        run: |
          echo "Release Branch Pushed: ${{ github.ref_name }}"
          echo "Current Time: $(date -u)"
