name: Branch Information

on:

  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'terraform/**'
      - '.github/**'
      - 'README.md'

jobs:
  development_branch_info:
    if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: install-databricks-cli
      #   uses: microsoft/install-databricks-cli@v2.1.0
    
      - name: update Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          job_id=${{vars.JOB_ID}}
          # Replace 'JOB_ID' with the actual Job ID and ensure the JSON is correctly formatted for your job
          job_update_json="{\"job_id\": $job_id, \"new_settings\": {\"git_source\": { \"branch\": \"$branch_name\"}}}"
          databricks jobs update --json "$job_update_json"

      - name: Echo Development Branch Name
        run: |
          echo "Development Branch Pushed: ${GITHUB_REF#refs/heads/}"

  release_branch_info:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo Release Branch Name and Current Time
        run: |
          echo "Release Branch Pushed: ${{ github.ref_name }}"
          echo "Current Time: $(date -u)"
